version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://192.168.10.152:8080');
        define('WP_SITEURL', 'http://192.168.10.152:8080');
    env_file:
      - .env.dev
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: wordpress_db
    restart: always
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
